language: python
python:
  - "2.7"

install:
  - pip install service-identity
  - pip install Jinja2==2.5.5
  - pip install Twisted==10.1.0
  - pip install argparse==1.1
  - pip install distribute==0.6.14
  - pip install mock==1.0.1
  - pip install pep8==1.5.7
  - pip install pyOpenSSL==0.14
  - pip install pyasn1==0.0.11a
  - pip install pycrypto==2.3
  - pip install wsgiref==0.1.2
  - pip install zope.interface==3.6.1
  - hg clone -u production-0.8 -b production-0.8 http://hg.mozilla.org/build/buildbot ~/buildbot
  - cd ~/buildbot/master
  - python setup.py install
  - git clone --depth 50 --branch=master git://github.com/mozilla/build-tools.git ~/tools
  - export PYTHONPATH=~/"tools/lib/python:${TRAVIS_BUILD_DIR%/*}"
  - pip freeze

script:
  - mv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR%/*}/buildbotcustom" || true
  - find "${TRAVIS_BUILD_DIR%/*}/buildbotcustom/test" -name '*.py' -print0 | xargs -0 -n 1 trial --reporter=verbose

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# notifications:
#   irc: "irc.mozilla.org#releng"
#   on_success: always
#   on_failure: always
