language: python
python:
  - "2.7"

install:
  - pip install pycrypto
  - pip install twisted
  - pip install Jinja2
  - pip install argparse
  - pip install pyasn1
  - pip install pep8
  - pip install mock
  - pip install pyopenssl
  - pip install service-identity
  - pip install trial
  - hg clone -u production-0.8 -b production-0.8 http://hg.mozilla.org/build/buildbot ~/buildbot
  - cd ~/buildbot/master
  - python setup.py install
  - git clone --depth 50 --branch=master git://github.com/mozilla/build-tools.git ~/tools
  - export PYTHONPATH=~/"tools/lib/python:${TRAVIS_BUILD_DIR%/*}"

script:
  - mv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR%/*}/buildbotcustom" || true
  - trial --reporter=verbose $(find "${TRAVIS_BUILD_DIR%/*}/buildbotcustom/test" -name '*.py')

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# notifications:
#   irc: "irc.mozilla.org#releng"
#   on_success: always
#   on_failure: always
